// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewContainerType struct {
	ID          *string `json:"id"`
	TenantID    string  `json:"tenantId"`
	Description string  `json:"description"`
}

type NewTenant struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type NewUser struct {
	ID       *string `json:"id"`
	TenantID string  `json:"tenantId"`
	Name     string  `json:"name"`
}
